//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Validator_Vertyachikh.Properties {
    
    
    /// <summary>
    /// by ryzenvpn/vertyachikh: класс предоставляет доступ к настройкам приложения через сгенерированное свойство Default.
    /// </summary>
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        /// <summary>
        /// by ryzenvpn/vertyachikh: единственный общий экземпляр настроек приложения.
        /// </summary>
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        /// <summary>
        /// by ryzenvpn/vertyachikh: возвращает общий экземпляр настроек, безопасный для использования в приложении.
        /// </summary>
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
